// This file was generated by a tool. Modifying it will produce unexpected behavior

export interface IExportStyles {
  'description': string;

  'played': string;

  'result': string;

}

declare const strings: IExportStyles;

export default strings;